### ISSUE TITLE
Error using "run_in_reactor" in 1.8.0 that worked well in 1.7.0

### ISSUE THREAD

**Issue by 2mf** [itamarst/crochet#115]
use case:
```
@defer.inlineCallbacks
def do_stomething():
        yield do_something_else()

crochet.run_in_reactor(do_something)().wait()
```
exception in 1.8.0:
```
    def run_in_reactor(self, function):
        """
            A decorator that ensures the wrapped function runs in the
            reactor thread.
    
            When the wrapped function is called, an EventualResult is returned.
            """
        result = self._run_in_reactor(function)
        # Backwards compatibility; we could have used wrapt's version, but
        # older Crochet code exposed different attribute name:
        try:
>           result.wrapped_function = function
E           AttributeError: 'method' object has no attribute 'wrapped_function'

/usr/local/pyenv/versions/3.6.1/envs/python36/lib/python3.6/site-packages/crochet/_eventloop.py:469: AttributeError
```

**Comment by itamarst** [comment]
Oops. I thought I fixed that before releasing :(

Will try to get that fixed today or tomorrow.

**Comment by 2mf** [comment]
thanks

**Comment by itamarst** [comment]
Ah, I fixed this for Python 2, and I thought it wasn't an issue in Python 3... but apparently there's an edge case in Python 3 that I hadn't discovered.

**Comment by itamarst** [comment]
Released 1.9.0 with a fix. Let me know if it's still a problem.

**Comment by 2mf** [comment]
works for me. thanks
